# -*- coding: utf-8 -*-
"""Phishing_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vp-NE5P9alh1hyVCGVwFjGkAr4uBvIRp
"""

import re
def phishing_detector(url):
    risk_score = 0
    warnings = []

    # Check URL length
    if len(url) > 75:
        risk_score += 1
        warnings.append("URL is unusually long")
    # Check HTTPS
    if url.startswith("https://"):
        pass
    else:
        risk_score += 1
        warnings.append("Website does not use HTTPS")
    # Suspicious keywords
    suspicious_words = [
        "login",
        "verify",
        "update",
        "bank",
        "account",
        "password",
        "free",
        "reward"
    ]
    for word in suspicious_words:
        if word in url.lower():
            risk_score += 1
            warnings.append("Suspicious word found: " + word)
    # Check @ symbol
    if "@" in url:
        risk_score += 1
        warnings.append("URL contains @ symbol")

    # Check multiple special characters
    if re.search(r"[-_]{3,}", url):
        risk_score += 1
        warnings.append("Too many special characters")

    # Final result
    print("\nRisk Score:", risk_score)
    if risk_score <= 1:
        print("Result: SAFE URL")
    elif risk_score <= 3:
        print("Result: SUSPICIOUS URL")
    else:
        print("Result: PHISHING POSSIBLE")
    print("\nWarnings:")
    if warnings:
        for w in warnings:
            print("-", w)
    else:
        print("No suspicious activity detected")

# Main Program
website = input("Enter website URL: ")
phishing_detector(website)